== The story behind this solution pattern

InstaMedi, a fictional health tech company that builds portal for patients and doctors for its group of hospitals, has decided to move it's applications from a traditional hypervisor platform to Red Hat OpenShift Virtualization. This enables them to have a platform that addresses their current needs while also preparing them for future modernization and change all while enhancing the operational efficiency. Red Hat OpenShift Virtualization offers a compelling solution by allowing organizations to run both virtual machines (VMs) and containers on a single, unified platform. By migrating virtual machines from other platforms and running them on Red Hat OpenShift, they could get the most from their existing virtualization investments while taking advantage of cloud-native architectures, streamlined operations and management, and new development approaches. 

To ensure a smooth transition from traditional hypervisors like VMware vSphere to Red Hat OpenShift Virtualization, InstaMedi must adopt a phased migration strategy that minimizes downtime and disruption to its healthcare services. Given the critical nature of patient and doctor portals, maintaining uninterrupted access is essential. The traffic switchover from the services in the existing hypervisor to OpenShift Virtualization will be handled carefully to ensure zero downtime. This involves gradually redirecting traffic to services running on OpenShift virtualization while maintaining connectivity to the original VMs until the full migration is complete. Additionally, InstaMedi aims to reduce the complexity involved in building and managing complex networking systems. By doing so, InstaMedi can mitigate risks, maintain service continuity, and avoid disruptions to daily operations, all while efficiently transitioning to a more modern and scalable infrastructure.

== The Solution


InstaMedi decided to use implement *Red Hat Service Interconnect* as a key component of its migration strategy to simplify connectivity across its diverse environments. By leveraging the advanced Layer 7 addressing and routing capabilities of Service Interconnect, InstaMedi ensured seamless communication between its applications during and after the migration process. This solution allowed their applications to communicate effortlessly across both the traditional hypervisor platform and OpenShift Virtualization, even as components were gradually moved or updated. Service Interconnect's anycast/multicast capabilities, enabled multiple instances of a service deployed in different destinations to use the same service address. This streamlined routing of requests to instances of a single service, regardless of whether they were running - original hypervisor or OpenShift Virtualization. If a VM is disconnected or a service is undeployed post-migration, traffic is automatically and seamlessly switched over to newly migrated service instances that are using the same address, ensuring continuous operation without disruption.

== Additonal Context and Resources
* 
* https://www.redhat.com/en/engage/15-reasons-adopt-openshift-virtualization-ebook[15-reasons-adopt-openshift-virtualization-ebook]