= Solution Patterns: Minimize downtime when migrating your applications from hypervisor based environments to OpenShift Virtualization
:page-layout: home
:sectnums:
:sectlinks:
:doctype: book

Migrating applications from one platform to the other requires a thoughtful, phased approach. For example, let's consider an enterprise is transitioning from transitioning from traditional hypervisor solutions like VMware vSphere to OpenShift Virtualization. Factors such as application dependencies, regulatory compliance, budget constraints, and resource availability often necessitate a phased migration approach to minimize disruption and maximize the benefits.  This gradual shift allows organizations to mitigate risks and ensure continuity while migrating to OpenShift virtualization. The traffic switchover from services running on existing hypervisor platforms to OpenShift Virtualization must be disruption-free with zero downtime. Additionally, connectivity to the existing VMs in the hypervisor needs to be maintained until all components are migrated.

This solution pattern demonstrates how a locationless connectivity solution enabled by Red Hat Service interconnect can leveraged for a disruption free migration and switchover between environments (Vmware to Openshift Virtualization in this example) with almost zero downtime. 

*Contributors:* _Vamsi Ravula (Red Hat)_

++++
 <br>
++++
[NOTE]
====
Solutions Patterns help you understand the art of the possible with Red Hat's portfolio, and not intended to be used as is for production environments. You are welcome use any part of this solution pattern for your own workloads.
====
[#use-cases]
== Use cases

Though this pattern deals with moving applications and services, from traditional hypervisor platforms such as VMware to OpenShift virtualization, the same concepts can be applied to number of other use cases such as the ones listed below:

- Migration from an older version of OpenShift/Kubernetes to a newer version. Ex: OpenShift 3 to 4 migration
- Distributing and moving services across multiple kubernetes clusters (cloud or on-prem)without any downtime
- Moving applications across different kubernetes offerings. Ex: Vanilla kubernetes to OpenShift, AKS/EKS to OpenShift


include::01-pattern.adoc[]
